# -*- coding: utf-8 -*-
"""
Build the hosted GitHub Pages site from saved digests.

  docs/index.html         <- copy of the latest digest (homepage)
  docs/archive.html       <- auto-generated index of all past digests
  docs/archive/digest_YYYY-MM-DD.html <- copies of every digest ever saved
  docs/unsubscribe.html   <- (untouched, managed by pages.yml)

The daily workflow commits docs/ back to the repo, which triggers pages.yml
to redeploy the site to GitHub Pages.
"""
import os
import re
import shutil
from datetime import date
from html import escape

import config


DOCS_DIR = os.path.join(config.BASE_DIR, "docs")
ARCHIVE_DIR = os.path.join(DOCS_DIR, "archive")


def _ensure_dirs():
    os.makedirs(DOCS_DIR, exist_ok=True)
    os.makedirs(ARCHIVE_DIR, exist_ok=True)
    os.makedirs(config.DIGEST_DIR, exist_ok=True)


def _extract_date(filename):
    """'digest_2026-09-04.html' -> '2026-09-04'."""
    m = re.match(r"digest_(\d{4}-\d{2}-\d{2})\.html", filename)
    return m.group(1) if m else None


def _extract_summary(html):
    """Extract a short summary (deal counts) from a digest HTML file."""
    text = re.sub(r"<[^>]+>", " ", html)
    text = re.sub(r"\s+", " ", text)
    # try to find "X new/changed" and "Y still active" from the subject/comparison
    main = re.search(r"(\d+)\s+new\s*/?\s*changed", text, re.I)
    still = re.search(r"(\d+)\s+still\s*active", text, re.I)
    parts = []
    if main:
        parts.append(f"{main.group(1)} new/changed")
    if still:
        parts.append(f"{still.group(1)} still active")
    return ", ".join(parts) if parts else ""


def build():
    """Copy the latest digest to docs/index.html + docs/archive/, then
    regenerate docs/archive.html with links to all past digests."""
    _ensure_dirs()

    # find the latest digest
    digests = sorted(
        f for f in os.listdir(config.DIGEST_DIR)
        if f.startswith("digest_") and f.endswith(".html")
    )
    if not digests:
        print("[site] no digests found — skipping site build")
        return

    latest = digests[-1]
    latest_path = os.path.join(config.DIGEST_DIR, latest)
    latest_date = _extract_date(latest) or date.today().isoformat()

    # copy latest -> docs/index.html (homepage)
    shutil.copy2(latest_path, os.path.join(DOCS_DIR, "index.html"))

    # copy latest -> docs/archive/digest_YYYY-MM-DD.html
    archive_name = f"digest_{latest_date}.html"
    shutil.copy2(latest_path, os.path.join(ARCHIVE_DIR, archive_name))

    # also copy any digests that exist in data/digests/ but not yet in docs/archive/
    for f in digests:
        dest = os.path.join(ARCHIVE_DIR, f)
        if not os.path.exists(dest):
            shutil.copy2(os.path.join(config.DIGEST_DIR, f), dest)

    # generate archive.html
    archive_files = sorted(
        [f for f in os.listdir(ARCHIVE_DIR)
         if f.startswith("digest_") and f.endswith(".html")],
        reverse=True,  # newest first
    )

    rows = []
    for f in archive_files:
        d = _extract_date(f) or f
        fpath = os.path.join(ARCHIVE_DIR, f)
        try:
            with open(fpath, "r", encoding="utf-8") as fh:
                content = fh.read()
            summary = _extract_summary(content)
        except OSError:
            summary = ""
        label = d
        if f == archive_name:
            label += " (today)"
        rows.append(
            f"<tr>"
            f"<td style='padding:8px'><a href='archive/{escape(f)}'>{escape(label)}</a></td>"
            f"<td style='padding:8px;color:#666'>{escape(summary)}</td>"
            f"</tr>"
        )

    rows_html = "\n".join(rows) if rows else "<tr><td>No digests yet.</td></tr>"
    today = date.today().isoformat()
    archive_html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Riga flat deals — archive</title>
<style>
body{{font-family:Arial,sans-serif;color:#222;max-width:800px;margin:0 auto;padding:20px}}
h1{{color:#1a5276}}h2{{color:#2874a6}}
td,th{{border-bottom:1px solid #eee}}a{{color:#2874a6;text-decoration:none}}a:hover{{text-decoration:underline}}
.note{{color:#777;font-size:13px}}
table{{width:100%;border-collapse:collapse}}
</style></head><body>
<h1>Riga flat deals — archive</h1>
<p class="note">Districts: {', '.join(config.DISTRICTS.keys())} · Sources: ss.com, city24.lv</p>
<p><a href="index.html">← Back to today's deals</a></p>
<h2>All daily digests ({len(archive_files)} total)</h2>
<table>
<tr style="background:#f0f0f0"><th style="text-align:left;padding:8px">Date</th><th style="text-align:left;padding:8px">Summary</th></tr>
{rows_html}
</table>
<hr><p class="note">Generated by Flat_Searcher on {today}.
<a href="unsubscribe.html">Unsubscribe from emails</a></p>
</body></html>"""

    with open(os.path.join(DOCS_DIR, "archive.html"), "w", encoding="utf-8") as f:
        f.write(archive_html)

    print(f"[site] built: index.html (digest {latest_date}), "
          f"archive.html ({len(archive_files)} digests)")


if __name__ == "__main__":
    build()
